# Generated by Django 6.0.3 on 2026-04-01 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HNThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn_id', models.IntegerField(db_index=True, help_text='Hacker NewsのアイテムID', unique=True, verbose_name='HN ID')),
                ('title', models.TextField(verbose_name='タイトル')),
                ('url', models.URLField(blank=True, default='', help_text='外部リンクURL（self-postの場合は空）', verbose_name='URL')),
                ('author', models.CharField(blank=True, default='', max_length=255, verbose_name='投稿者')),
                ('is_investigated', models.BooleanField(default=False, help_text='エージェントによる調査が完了しているか', verbose_name='調査済み')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='初回検出日時')),
            ],
            options={
                'verbose_name': 'HNスレッド',
                'verbose_name_plural': 'HNスレッド',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='HNThreadSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='スコア')),
                ('num_comments', models.IntegerField(verbose_name='コメント数')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='hn_agent.hnthread', verbose_name='スレッド')),
            ],
            options={
                'verbose_name': 'スナップショット',
                'verbose_name_plural': 'スナップショット',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['thread', 'fetched_at'], name='hn_agent_hn_thread__0b369c_idx')],
            },
        ),
    ]
