# Generated by Django 6.0.3 on 2026-04-01 18:15

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('detective', 'Detective'), ('hypothesis', 'Hypothesis'), ('memory', 'Memory')], max_length=50, verbose_name='エージェント種別')),
                ('result', models.JSONField(verbose_name='調査結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='hn_agent.hnthread', verbose_name='スレッド')),
            ],
            options={
                'verbose_name': '調査結果',
                'verbose_name_plural': '調査結果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='text-embedding-3-small (1536次元)', verbose_name='埋め込みベクトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='hn_agent.hnthread', verbose_name='スレッド')),
            ],
            options={
                'verbose_name': 'スレッド埋め込み',
                'verbose_name_plural': 'スレッド埋め込み',
            },
        ),
    ]
