# Generated by Django 6.0.3 on 2026-04-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_agent', '0002_add_embedding_and_investigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HNAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='この設定を識別するための名前', max_length=255, unique=True, verbose_name='設定名')),
                ('is_active', models.BooleanField(default=False, help_text='この設定を有効にする（有効にできるのは1つの設定のみ）', verbose_name='有効')),
                ('embedding_model', models.CharField(default='text-embedding-3-small', help_text='OpenAI Embedding APIのモデル名', max_length=255, verbose_name='Embeddingモデル')),
                ('embedding_dimensions', models.IntegerField(default=1536, help_text='Embeddingベクトルの次元数', verbose_name='Embedding次元数')),
                ('score_threshold', models.IntegerField(default=100, help_text='調査をトリガーするスコアの閾値', verbose_name='スコア閾値')),
                ('velocity_threshold', models.FloatField(default=50.0, help_text='調査をトリガーするスコア上昇速度の閾値', verbose_name='速度閾値（ポイント/時間）')),
                ('similarity_threshold', models.FloatField(default=0.85, help_text='過去スレッド検索のcosine similarity閾値（0-1）', verbose_name='類似度閾値')),
                ('poll_interval_seconds', models.IntegerField(default=600, help_text='HNフロントページのポーリング間隔', verbose_name='ポーリング間隔（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'HN Agent設定',
                'verbose_name_plural': 'HN Agent設定',
            },
        ),
    ]
