# Generated by Django 6.0.3 on 2026-04-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hn_agent', '0003_hnagentconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hnagentconfig',
            name='embedding_dimensions',
        ),
        migrations.RemoveField(
            model_name='hnagentconfig',
            name='embedding_model',
        ),
    ]
