# Generated by Django 6.0.3 on 2026-04-02 13:04

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_agent', '0004_remove_hnagentconfig_embedding_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hnagentconfig',
            name='embedding_dimensions',
            field=models.IntegerField(default=1536, help_text='Embedding APIに渡す出力次元数。DBのベクトルカラムもこの値に合わせる必要がある。text-embedding-3-small: 最大1536、text-embedding-3-large: 最大3072', verbose_name='Embedding次元数'),
        ),
        migrations.AlterField(
            model_name='threadembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(help_text='次元数はHN Agent設定のembedding_dimensionsに依存', verbose_name='埋め込みベクトル'),
        ),
    ]
