# Generated by Django 6.0.3 on 2026-04-05 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_agent', '0005_hnagentconfig_embedding_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hnagentconfig',
            name='reasoning_effort',
            field=models.CharField(choices=[('low', '低（ツール選択等の単純判断向け）'), ('medium', '中'), ('high', '高（複雑な判断向け）')], default='low', help_text='Orchestratorの推論トークン量を制御（コストに影響）', max_length=10, verbose_name='推論深度'),
        ),
        migrations.AlterField(
            model_name='hnagentconfig',
            name='embedding_dimensions',
            field=models.IntegerField(default=1536, help_text='Embedding APIに渡す出力次元数。DBのベクトルカラムもこの値に合わせる必要がある。text-embedding-3-small: 最大1536、text-embedding-3-large: 最大3072', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3072)], verbose_name='Embedding次元数'),
        ),
        migrations.AlterField(
            model_name='hnagentconfig',
            name='poll_interval_seconds',
            field=models.IntegerField(default=600, help_text='HNフロントページのポーリング間隔（最低60秒）', validators=[django.core.validators.MinValueValidator(60)], verbose_name='ポーリング間隔（秒）'),
        ),
        migrations.AlterField(
            model_name='hnagentconfig',
            name='score_threshold',
            field=models.IntegerField(default=100, help_text='調査をトリガーするスコアの閾値', validators=[django.core.validators.MinValueValidator(1)], verbose_name='スコア閾値'),
        ),
        migrations.AlterField(
            model_name='hnagentconfig',
            name='similarity_threshold',
            field=models.FloatField(default=0.85, help_text='過去スレッド検索のcosine similarity閾値（0-1）', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='類似度閾値'),
        ),
        migrations.AlterField(
            model_name='hnagentconfig',
            name='velocity_threshold',
            field=models.FloatField(default=50.0, help_text='調査をトリガーするスコア上昇速度の閾値', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='速度閾値（ポイント/時間）'),
        ),
    ]
