# Generated by Django 6.0.3 on 2026-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_agent', '0006_hnagentconfig_reasoning_effort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hnagentconfig',
            name='reasoning_effort',
            field=models.CharField(blank=True, choices=[('', '無効（モデル非対応時）'), ('low', '低（ツール選択等の単純判断向け）'), ('medium', '中'), ('high', '高（複雑な判断向け）')], default='low', help_text='Orchestratorの推論トークン量を制御（コストに影響）。モデルが非対応の場合は「無効」を選択', max_length=10, verbose_name='推論深度'),
        ),
    ]
