# Generated by Django 6.0.3 on 2026-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_agent', '0007_alter_hnagentconfig_reasoning_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hnthread',
            name='url',
            field=models.URLField(blank=True, default='', help_text='外部リンクURL（self-postの場合は空）', max_length=2048, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='agent_type',
            field=models.CharField(choices=[('detective', 'Detective'), ('memory', 'Memory')], max_length=50, verbose_name='エージェント種別'),
        ),
    ]
