# Generated by Django 6.0.3 on 2026-04-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hn_agent', '0008_url_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hnagentconfig',
            name='embedding_dimensions',
        ),
        migrations.RemoveField(
            model_name='hnagentconfig',
            name='similarity_threshold',
        ),
        migrations.AlterField(
            model_name='investigation',
            name='agent_type',
            field=models.CharField(choices=[('detective', 'Detective')], max_length=50, verbose_name='エージェント種別'),
        ),
        migrations.DeleteModel(
            name='ThreadEmbedding',
        ),
    ]
