# Generated by Django 6.0.3 on 2026-04-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hn_agent', '0009_remove_memory_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investigation',
        ),
    ]
