# Generated by Django 6.0 on 2026-01-26 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0005_remove_user_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreetingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='API呼び出し時に指定する識別子（例: morning, evening）', max_length=50, unique=True, verbose_name='設定名')),
                ('display_name', models.CharField(help_text='管理画面での表示名', max_length=100, verbose_name='表示名')),
                ('use_weather', models.BooleanField(default=False, help_text='{{weather}} プレースホルダーを有効にする', verbose_name='天気情報を使用')),
                ('use_events', models.BooleanField(default=False, help_text='{{events}} プレースホルダーを有効にする', verbose_name='予定情報を使用')),
                ('use_datetime', models.BooleanField(default=True, help_text='{{datetime}} プレースホルダーを有効にする', verbose_name='日時情報を使用')),
                ('area_code', models.CharField(blank=True, default='', help_text='6桁の数字（例: 130010）。天気情報を使用する場合は必須', max_length=10, validators=[django.core.validators.RegexValidator(message='予報区コードは6桁の数字で入力してください', regex='^\\d{6}$')], verbose_name='予報区コード')),
                ('tts_enabled', models.BooleanField(default=False, verbose_name='音声合成を有効にする')),
                ('tts_model', models.CharField(blank=True, default='', max_length=100, verbose_name='TTSモデル')),
                ('tts_style', models.CharField(default='Neutral', max_length=50, verbose_name='TTSスタイル')),
                ('tts_style_weight', models.FloatField(default=1.0, verbose_name='スタイル強度')),
                ('tts_speed', models.FloatField(default=1.0, verbose_name='話速')),
                ('tts_sdp_ratio', models.FloatField(default=0.2, verbose_name='SDP比率')),
                ('tts_noise_scale', models.FloatField(default=0.6, verbose_name='ノイズスケール')),
                ('tts_noise_scale_w', models.FloatField(default=0.8, verbose_name='ノイズスケールW')),
                ('system_prompt', models.TextField(verbose_name='システムプロンプト')),
            ],
            options={
                'verbose_name': '挨拶設定',
                'verbose_name_plural': '挨拶設定',
            },
        ),
        migrations.DeleteModel(
            name='EveningGreetingConfig',
        ),
        migrations.DeleteModel(
            name='MorningGreetingConfig',
        ),
        migrations.DeleteModel(
            name='WelcomeHomeGreetingConfig',
        ),
    ]
