# Generated by Django 6.0.3 on 2026-04-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiconfig',
            name='embedding_model',
            field=models.CharField(default='text-embedding-3-small', help_text='Embedding生成に使用するモデル（例：text-embedding-3-small）', max_length=255, verbose_name='Embeddingモデル'),
        ),
        migrations.AlterField(
            model_name='openaiconfig',
            name='model',
            field=models.CharField(default='gpt-4o-mini', help_text='チャット補完に使用するモデル（例：gpt-4o-mini, gpt-4o）', max_length=255, verbose_name='チャットモデル'),
        ),
    ]
