# Generated by Django 6.0.3 on 2026-04-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0002_openaiconfig_embedding_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('orchestrator', 'HN Agent Orchestrator'), ('detective', 'HN Agent Detective'), ('talk', 'Talk（会話生成）'), ('embedding', 'Embedding生成')], help_text='LLMを使用するサービスの識別名', max_length=50, unique=True, verbose_name='サービス名')),
                ('model_alias', models.CharField(help_text='LiteLLM Proxyのmodel_name（例: gpt-4o, kimi-k2.5, claude-sonnet）', max_length=100, verbose_name='モデルエイリアス')),
                ('is_active', models.BooleanField(default=True, help_text='このサービス設定を有効にする', verbose_name='有効')),
                ('timeout', models.IntegerField(default=60, help_text='APIリクエストのタイムアウト秒数', verbose_name='タイムアウト（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'LLMサービス設定',
                'verbose_name_plural': 'LLMサービス設定',
            },
        ),
    ]
