# Generated by Django 6.0.3 on 2026-04-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0003_add_llm_service_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmserviceconfig',
            name='_encrypted_proxy_api_key',
            field=models.TextField(blank=True, db_column='encrypted_proxy_api_key', default='', help_text='LiteLLM Virtual Key（未設定時はLITELLM_MASTER_KEY環境変数を使用）', verbose_name='暗号化されたAPIキー'),
        ),
    ]
