# Generated by Django 6.0.3 on 2026-04-11 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0004_add_proxy_api_key_to_service_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='この設定の識別名（例: Kimi K2.5 本番, GPT-4o テスト）', max_length=100, unique=True, verbose_name='設定名')),
                ('model_alias', models.CharField(help_text='LiteLLM Proxyのmodel_name（例: bedrock/moonshotai.kimi-k2.5）', max_length=100, verbose_name='モデルエイリアス')),
                ('_encrypted_proxy_api_key', models.TextField(blank=True, db_column='encrypted_proxy_api_key', default='', help_text='LiteLLM Virtual Key（未設定時はLITELLM_MASTER_KEY環境変数を使用）', verbose_name='暗号化されたAPIキー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'LLM設定',
                'verbose_name_plural': 'LLM設定',
            },
        ),
        migrations.AddField(
            model_name='llmserviceconfig',
            name='provider_config',
            field=models.ForeignKey(blank=True, help_text='使用するLLMプロバイダー設定を選択', null=True, on_delete=django.db.models.deletion.PROTECT, to='llm_config.llmproviderconfig', verbose_name='LLM設定'),
        ),
    ]
