# Generated by Django 6.0.3 on 2026-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0007_remove_old_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmserviceconfig',
            name='service_name',
            field=models.CharField(choices=[('orchestrator', 'HN Agent Orchestrator'), ('detective', 'HN Agent Detective'), ('talk', 'Talk（会話生成）')], help_text='LLMを使用するサービスの識別名', max_length=50, unique=True, verbose_name='サービス名'),
        ),
    ]
