# Generated by Django 6.0 on 2025-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSGraphConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(help_text='Azure AD（Microsoft Entra ID）のテナントID', max_length=255, verbose_name='テナントID')),
                ('client_id', models.CharField(help_text='Azure ADアプリケーションのクライアントID', max_length=255, verbose_name='クライアントID')),
                ('cert_thumbprint', models.CharField(help_text='証明書のサムプリント（拇印）', max_length=255, verbose_name='証明書サムプリント')),
                ('target_user', models.CharField(help_text='OneDriveにアクセスする対象ユーザーのメールアドレスまたはユーザーID', max_length=255, verbose_name='対象ユーザー')),
                ('_encrypted_private_key', models.TextField(blank=True, db_column='encrypted_private_key', default='', verbose_name='暗号化された秘密鍵')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Microsoft Graph API設定',
                'verbose_name_plural': 'Microsoft Graph API設定',
            },
        ),
    ]
