# Generated by Django 6.0 on 2025-12-06 17:14

from django.db import migrations, models


def activate_existing_config(apps, schema_editor):
    """既存の設定を有効にする"""
    MSGraphConfig = apps.get_model("onedrive", "MSGraphConfig")
    # 既存の設定があれば最初の1つを有効にする
    MSGraphConfig.objects.filter(pk=1).update(is_active=True)


def deactivate_existing_config(apps, schema_editor):
    """既存の設定を無効にする（ロールバック用）"""
    MSGraphConfig = apps.get_model("onedrive", "MSGraphConfig")
    MSGraphConfig.objects.all().update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("onedrive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="msgraphconfig",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="この設定を有効にする（有効にできるのは1つの設定のみ）",
                verbose_name="有効",
            ),
        ),
        migrations.AddField(
            model_name="msgraphconfig",
            name="name",
            field=models.CharField(
                default="デフォルト設定",
                help_text="この設定を識別するための名前（例：本番環境、テスト環境）",
                max_length=255,
                unique=True,
                verbose_name="設定名",
            ),
        ),
        # 既存データのis_activeをTrueに設定
        migrations.RunPython(activate_existing_config, deactivate_existing_config),
    ]
