# Generated by Django 6.0 on 2026-01-10 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morninggreetingconfig',
            name='rail_ids',
        ),
        migrations.AlterField(
            model_name='morninggreetingconfig',
            name='area_code',
            field=models.CharField(help_text='6桁の数字（例: 130010）', max_length=10, validators=[django.core.validators.RegexValidator(message='予報区コードは6桁の数字で入力してください', regex='^\\d{6}$')], verbose_name='予報区コード'),
        ),
    ]
