# Generated by Django 6.0 on 2026-01-13 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_add_evening_greeting_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeHomeGreetingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('area_code', models.CharField(help_text='6桁の数字（例: 130010）', max_length=10, validators=[django.core.validators.RegexValidator(message='予報区コードは6桁の数字で入力してください', regex='^\\d{6}$')], verbose_name='予報区コード')),
                ('tts_enabled', models.BooleanField(default=False, verbose_name='音声合成を有効にする')),
                ('tts_model', models.CharField(blank=True, default='', max_length=100, verbose_name='TTSモデル')),
                ('tts_style', models.CharField(default='Neutral', max_length=50, verbose_name='TTSスタイル')),
                ('tts_style_weight', models.FloatField(default=1.0, verbose_name='スタイル強度')),
                ('tts_speed', models.FloatField(default=1.0, verbose_name='話速')),
                ('tts_sdp_ratio', models.FloatField(default=0.2, verbose_name='SDP比率')),
                ('tts_noise_scale', models.FloatField(default=0.6, verbose_name='ノイズスケール')),
                ('tts_noise_scale_w', models.FloatField(default=0.8, verbose_name='ノイズスケールW')),
                ('system_prompt', models.TextField(verbose_name='システムプロンプト')),
                ('user_prompt', models.TextField(verbose_name='ユーザープロンプト')),
            ],
            options={
                'verbose_name': 'おかえりのあいさつ設定',
                'verbose_name_plural': 'おかえりのあいさつ設定',
            },
        ),
    ]
