# Generated by Django 6.0 on 2026-01-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0004_add_welcome_home_greeting_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eveninggreetingconfig',
            name='user_prompt',
        ),
        migrations.RemoveField(
            model_name='morninggreetingconfig',
            name='user_prompt',
        ),
        migrations.RemoveField(
            model_name='welcomehomegreetingconfig',
            name='user_prompt',
        ),
    ]
