# Generated by Django 6.0 on 2026-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0006_unified_greeting_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingconfig',
            name='tts_format',
            field=models.CharField(choices=[('wav', 'WAV'), ('mp3', 'MP3'), ('ogg', 'OGG')], default='mp3', help_text='出力音声のフォーマット（デフォルト: MP3）', max_length=10, verbose_name='音声フォーマット'),
        ),
    ]
