# Generated by Django 6.0 on 2026-02-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0007_greetingconfig_tts_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greetingconfig',
            name='tts_format',
            field=models.CharField(choices=[('wav', 'WAV'), ('mp3', 'MP3'), ('ogg', 'OGG')], default='wav', help_text='出力音声のフォーマット（デフォルト: WAV）', max_length=10, verbose_name='音声フォーマット'),
        ),
    ]
