# Generated by Django 6.0.3 on 2026-04-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TavilyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='この設定を識別するための名前', max_length=255, unique=True, verbose_name='設定名')),
                ('is_active', models.BooleanField(default=False, help_text='この設定を有効にする（有効にできるのは1つの設定のみ）', verbose_name='有効')),
                ('_encrypted_api_key', models.TextField(blank=True, db_column='encrypted_api_key', default='', verbose_name='暗号化されたAPIキー')),
                ('timeout', models.IntegerField(default=30, help_text='APIリクエストのタイムアウト秒数', verbose_name='タイムアウト（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Tavily API設定',
                'verbose_name_plural': 'Tavily API設定',
            },
        ),
    ]
