# Generated by Django 6.0.3 on 2026-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LangfusePromptRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Django 内で一意に識別する名前（例: hn-agent-orchestrator-system）', max_length=100, unique=True, verbose_name='識別名')),
                ('langfuse_prompt_name', models.CharField(help_text='Langfuse 上で登録されているプロンプト名', max_length=200, verbose_name='Langfuseプロンプト名')),
                ('label', models.CharField(default='production', help_text='Langfuse のプロンプトラベル（production, staging 等）', max_length=50, verbose_name='ラベル')),
                ('fallback_text', models.TextField(blank=True, default='', help_text='Langfuse 接続失敗・プロンプト未登録時に使用するテキスト', verbose_name='フォールバックテキスト')),
                ('description', models.CharField(blank=True, default='', help_text='このプロンプトの用途説明', max_length=255, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Langfuseプロンプト参照',
                'verbose_name_plural': 'Langfuseプロンプト参照',
                'ordering': ['name'],
            },
        ),
    ]
