# Generated by Django 6.0 on 2026-01-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_remove_rail_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveningGreetingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('tts_enabled', models.BooleanField(default=False, verbose_name='音声合成を有効にする')),
                ('tts_model', models.CharField(blank=True, default='', max_length=100, verbose_name='TTSモデル')),
                ('tts_style', models.CharField(default='Neutral', max_length=50, verbose_name='TTSスタイル')),
                ('tts_style_weight', models.FloatField(default=1.0, verbose_name='スタイル強度')),
                ('tts_speed', models.FloatField(default=1.0, verbose_name='話速')),
                ('tts_sdp_ratio', models.FloatField(default=0.2, verbose_name='SDP比率')),
                ('tts_noise_scale', models.FloatField(default=0.6, verbose_name='ノイズスケール')),
                ('tts_noise_scale_w', models.FloatField(default=0.8, verbose_name='ノイズスケールW')),
                ('system_prompt', models.TextField(verbose_name='システムプロンプト')),
                ('user_prompt', models.TextField(verbose_name='ユーザープロンプト')),
            ],
            options={
                'verbose_name': '夜のあいさつ設定',
                'verbose_name_plural': '夜のあいさつ設定',
            },
        ),
    ]
