# Generated by Django 6.0.4 on 2026-04-19 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0013_make_prompt_refs_required_remove_textfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkconfig',
            name='use_datetime',
        ),
        migrations.RemoveField(
            model_name='talkconfig',
            name='use_events',
        ),
        migrations.RemoveField(
            model_name='talkconfig',
            name='use_weather',
        ),
        migrations.AlterField(
            model_name='talkconfig',
            name='area_code',
            field=models.CharField(blank=True, default='', help_text='6桁の数字（例: 130010）。プロンプトに `{{weather}}` を含める場合は必須', max_length=10, validators=[django.core.validators.RegexValidator(message='予報区コードは6桁の数字で入力してください', regex='^\\d{6}$')], verbose_name='予報区コード'),
        ),
    ]
