# Generated by Django 6.0.4 on 2026-04-26 03:05

import django.db.models.deletion
import features.talk.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0014_remove_talkconfig_use_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', help_text='初回応答後に LLM で要約生成。手動編集も可能', max_length=120, verbose_name='タイトル')),
                ('config_name', models.CharField(help_text='セッション作成時に固定。途中変更不可', max_length=50, verbose_name='プリセット名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'チャットセッション',
                'verbose_name_plural': 'チャットセッション',
                'db_table': 'talk_chatsession',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='セッション内の連番')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=20)),
                ('content', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=features.talk.models.chat_audio_upload_path, verbose_name='音声ファイル')),
                ('audio_format', models.CharField(blank=True, default='', max_length=10)),
                ('audio_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='talk.chatsession')),
            ],
            options={
                'verbose_name': 'チャットメッセージ',
                'verbose_name_plural': 'チャットメッセージ',
                'db_table': 'talk_chatmessage',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='talk_chatse_user_id_2484c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='uniq_chatmessage_session_sequence'),
        ),
    ]
